FROM node:24-alpine

WORKDIR /app

COPY package.json /app/package.json
COPY .yarnrc.yml /app
COPY yarn.lock /app
COPY tsconfig.json /app
COPY vitest.config.mts /app
COPY vitest.integration.setup.mts /app
COPY src /app/src
COPY libs /app/libs

RUN corepack enable

RUN --mount=type=secret,id=npm_token \
    export NPM_AUTH_TOKEN="$(cat /run/secrets/npm_token)" && \
    yarn workspaces focus

CMD ["yarn", "vitest", "--project", "integration", "--run"]
