process.env.NEXT_PUBLIC_RUNTIME_ENV = 'local'
process.env.USE_LOCAL_SYK_INN_API = 'true'
process.env.HELSEID_URL = 'http://localhost:3000/api/mocks/helseid'
process.env.SYK_INN_PUBLIC_KEY_JWK = '{}'
process.env.SYK_INN_PRIVATE_KEY_JWK = '{}'
