apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: syk-inn
  namespace: tsm
  labels:
    team: tsm
spec:
  image: {{image}}
  ingresses:
    - 'https://www.nav.no/samarbeidspartner/sykmelding'
  valkey:
    - instance: syk-inn
      access: readwrite
  port: 3000
  replicas:
    min: 2
    max: 4
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  liveness:
    path: /samarbeidspartner/sykmelding/api/internal/is_alive
  readiness:
    path: /samarbeidspartner/sykmelding/api/internal/is_ready
  preStopHook:
    http:
      path: /samarbeidspartner/sykmelding/api/internal/pre_stop
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: 'tsm-unleash-api.nav.cloud.nais.io'
        - host: 'fhirapi.public.webmed.no'
      rules:
        - application: syk-inn-api
        - application: tsm-pdl-cache
        - application: logging
          namespace: nais-system
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
  envFrom:
    - secret: tsm-syk-inn-epj-secrets
    - secret: tsm-unleash-api-token
