apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: syk-inn
  namespace: tsm
  labels:
    team: tsm
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: tsm
  secretName: tsm-unleash-api-token
  environment: {{environment}}
