apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: syk-inn
  namespace: tsm
  labels:
    team: tsm
spec:
  image: {{image}}
  login:
    provider: openid
    enforce:
      enabled: true
      excludePaths:
        - /samarbeidspartner/sykmelding/fhir/**
        - /samarbeidspartner/sykmelding/api/**
  ingresses:
    - 'https://www.ekstern.dev.nav.no/samarbeidspartner/sykmelding'
  valkey:
    - instance: syk-inn
      access: readwrite
  port: 3000
  replicas:
    min: 1
    max: 2
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  prometheus:
    enabled: true
    path: /samarbeidspartner/sykmelding/api/internal/metrics
  liveness:
    path: /samarbeidspartner/sykmelding/api/internal/is_alive
  readiness:
    path: /samarbeidspartner/sykmelding/api/internal/is_ready
  preStopHook:
    http:
      path: /samarbeidspartner/sykmelding/api/internal/pre_stop
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: 'tsm-unleash-api.nav.cloud.nais.io'
        - host: 'fhir-api-auth.public.webmedepj.no'
        - host: 'helseid-sts.test.nhn.no'
      rules:
        - application: syk-inn-api
        - application: tsm-pdl-cache
        # Team Logs: https://docs.nais.io/observability/logging/how-to/team-logs/
        - application: logging
          namespace: nais-system
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
  envFrom:
    - secret: login-config-syk-inn
    - secret: tsm-syk-inn-epj-secrets
    - secret: tsm-syk-inn-slack-secrets
    - secret: tsm-unleash-api-token
