apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: syk-inn
  namespace: tsm
  labels:
    team: tsm
spec:
  image: {{image}}
  login:
    provider: openid
    enforce:
      enabled: true
      excludePaths:
        - /samarbeidspartner/sykmelding/fhir/**
        - /samarbeidspartner/sykmelding/api/**
  ingresses:
    - 'https://www.ekstern.dev.nav.no/samarbeidspartner/sykmelding'
  valkey:
    # Same valkey as syk-inn, will be owned by syk-inn because it created it
    - instance: syk-inn
      access: readwrite
  port: 3000
  replicas:
    min: 1
    max: 2
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  liveness:
    path: /samarbeidspartner/sykmelding/api/internal/is_alive
  readiness:
    path: /samarbeidspartner/sykmelding/api/internal/is_ready
  preStopHook:
    http:
      path: /samarbeidspartner/sykmelding/api/internal/pre_stop
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: syk-inn-wonderwall
    outbound:
      external:
        - host: 'tsm-unleash-api.nav.cloud.nais.io'
        - host: 'fhir-api-auth.public.webmedepj.no'
        - host: 'helseid-sts.test.nhn.no'
        - host: 'tsm-unleash-api.nav.cloud.nais.io'
        # TODO: Remove
        - host: 'launch.smarthealthit.org'
      rules:
        - application: syk-inn-api
        - application: tsm-pdl-cache
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
  secureLogs:
    enabled: true
  envFrom:
    - secret: login-config-syk-inn
    - secret: tsm-unleash-api-token
