apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: syk-inn
  namespace: tsm
  labels:
    team: tsm
spec:
  image: {{image}}
  port: 3000
  replicas:
    min: 1
    max: 2
  redis:
    - instance: syk-inn
      access: readwrite
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  liveness:
    path: /samarbeidspartner/sykmelding/api/internal/is_alive
  readiness:
    path: /samarbeidspartner/sykmelding/api/internal/is_ready
  preStopHook:
    http:
      path: /samarbeidspartner/sykmelding/api/internal/pre_stop
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: syk-inn-wonderwall
    outbound:
      external:
        - host: 'fhirapi.public.webmedepj.no'
        - host: 'helseid-sts.test.nhn.no'
      rules:
        - application: syk-inn-api
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
