apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: syk-inn
  namespace: tsm
  labels:
    team: tsm
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://www.ekstern.dev.nav.no/samarbeidspartner/sykmelding'
  replicas:
    min: 2
    max: 2
  redis:
    - instance: syk-inn
      access: readwrite
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  liveness:
    path: /samarbeidspartner/sykmelding/api/internal/is_alive
  readiness:
    path: /samarbeidspartner/sykmelding/api/internal/is_ready
  preStopHook:
    http:
      path: /samarbeidspartner/sykmelding/api/internal/pre_stop
  accessPolicy:
    outbound:
      external:
        - host: 'fhirapi.public.webmedepj.no'
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
