name: Build & Deploy Demo App
on: push

env:
  APP: syk-inn
  BASE_PATH: /samarbeidspartner/sykmelding

permissions:
  contents: read
  id-token: write

jobs:
  build-demo:
    if: github.ref_name == 'main' || startsWith(github.ref_name, 'demo')
    name: Build for demo
    runs-on: ubuntu-latest
    permissions:
      packages: 'write'
      contents: 'read'
      id-token: 'write'
    outputs:
      image: ${{ steps.build-and-publish.outputs.image }}
    steps:
      - uses: navikt/teamsykmelding-github-actions-workflows/actions/next-to-docker@main
        id: build-and-publish
        with:
          app: ${{ env.APP }}
          env: demo
          team: tsm
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-demo-main:
    if: github.ref_name == 'main'
    name: Deploy main to demo
    environment:
      name: demo-main
      url: https://${{ env.APP }}.ekstern.dev.nav.no${{ env.BASE_PATH }}
    runs-on: ubuntu-latest
    needs: [build-demo]
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/nais-demo.yaml
          VAR: image=${{ needs.build-demo.outputs.image }},ingress=https://${{ env.APP }}.ekstern.dev.nav.no${{ env.BASE_PATH }},appname=${{ env.APP }},replicas=1,branchState=alive
