name: Deploy Unleash token
on:
  push:
    paths:
      - .github/workflows/deploy-unleash-token.yml
      - .nais/nais-unleash-token.yaml
    branches:
      - main

permissions:
  id-token: write

jobs:
  deploy-unleash-token-dev:
    name: Deploy unleash token to dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-unleash-token.yaml
          VAR: environment=development

  deploy-unleash-token-prod:
    name: Deploy unleash token to prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais-unleash-token.yaml
          VAR: environment=production
