name: Deploy Wonderwall
on:
  push:
    paths:
      - .github/workflows/deploy-wonderwall.yml
      - .nais/nais-dev-wonderwall.yaml
    branches:
      - main

permissions:
  id-token: write

jobs:
  deploy-wonderwall-dev:
    name: Deploy wonderwall in dev
    environment:
      name: wonderwall-dev
      url: https://www.ekstern.dev.nav.no/samarbeidspartner/sykmelding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-dev-wonderwall.yaml
